server:
  ingress:
    enabled: false

controller:
  replicaCount: 1

repoServer:
  replicaCount: 1

applicationSet:
  enabled: true

configs:
  rbac:
    policy.csv: |
      g, admin, role:admin
      g, huseyindenizkivrak@gmail.com, role:admin
    scopes: '[groups, email]'

notifications:
  enabled: true

crds:
  install: false
  keep: false
