apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: sample-dotnet-wf-staging-image-automation
  namespace: flux-system
spec:
  interval: "5m0s"

  sourceRef:
    kind: GitRepository
    name: gitopslab
    namespace: flux-system
    
  git:
    checkout:
      ref:
        branch: "main"
    commit:
      author:
        email: "huseyindenizkivrak@gmail.com"
        name: "Flux Automation Bot"
  update:
    path: "flux/apps/local-staging/sample-dotnet/wf.yaml"
    strategy: "Setters"