apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prometheus-production-vs
  namespace: istio-system
spec:
  hosts:
    - "prome.prod.local"
  gateways:
    - istio-ingressgateway-production
  http:
    - route:
        - destination:
            host: mon-prometheus-production-server.monitoring.svc.cluster.local
            port:
              number: 80
