apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: prometheus-staging-vs
  namespace: istio-system
spec:
  hosts:
    - "prometheus.staging.local"
  gateways:
    - istio-ingressgateway-staging
  http:
    - route:
        - destination:
            host: mon-prometheus-staging-server.monitoring.svc.cluster.local
            port:
              number: 80
