service:
  type: LoadBalancer
  loadBalancerIP: "172.17.0.151"
  ports:
    - name: status-port
      port: 15023
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 8083
      protocol: TCP
      targetPort: 80
    - name: https
      port: 44303
      protocol: TCP
      targetPort: 443
env:
  ISTIO_META_MAX_REQUEST_HEADERS_KB: "32"      