apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon-prometheus-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 27.10.0
      helm:
        valueFiles:
          - values.yaml
          - $values/argocd/local-staging/monitoring/values/prometheus-values.yaml
    - repoURL: https://github.com/huseyindeniz/gitops-lab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/huseyindeniz/gitops-lab.git
      targetRevision: main
      path: "argocd/raw-manifests/local-staging/monitoring/prometheus"
      directory:
        recurse: true
  destination:
    server: "https://172.17.0.5:8443"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
