apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway-staging
  namespace: "argocd"
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: "1.28.0"
      chart: "gateway"
      helm:
        valueFiles:
          - "$values/argocd/local-staging/istio/values/istio-ingressgateway-values.yaml"
    - repoURL: https://github.com/huseyindeniz/gitops-lab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/huseyindeniz/gitops-lab.git
      targetRevision: main
      path: "argocd/raw-manifests/local-staging/istio"
      directory:
        recurse: true
  destination:
    server: "https://172.17.0.5:8443"
    namespace: "istio-system"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
