name: Harbor - Image Test - Build and push Docker images

on:
  workflow_dispatch:

jobs:

  build-push:
    runs-on: arc-runner-local-staging
    steps:
      - name: Get current timestamp
        run: |
          export LC_ALL=C
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish Docker image to Harbor
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: library/harbor-image-test
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
          registry: harbor.staging.local:30388
          tags: "${{ env.TIMESTAMP }}"
          dockerfile: apps/harbor-image-test/Dockerfile
          context: apps/harbor-image-test
